theme: jekyll-theme-yat

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-spaceship

title: Free Russia. Cyprus

facebook:
  publisher: https://www.facebook.com/nowarcy

social:
  name: Free Russia. Cyprus
  links:
    - https://www.facebook.com/nowarcy
    - https://www.instagram.com/nowarcyprus/
    - https://www.facebook.com/groups/cybrt
    - https://t.me/nowarcy
